### ISSUE TITLE
custom post or page link in menu

### ISSUE THREAD

**Issue by HsounaZinoubi** [rdlabo/ionic-wpcom#3]
Hello
it is possible to add custom post or page link in menu?
thanks

**Comment by rdlabo** [comment]
You can edit sidebar.

https://github.com/rdlabo/ionic-wpcom/tree/master/src/pages/template-parts/sidebar

**Comment by HsounaZinoubi** [comment]
can you please make an example on how to do this ?

**Comment by rdlabo** [comment]
This is external link sample.
https://github.com/rdlabo/ionic-wpcom/blob/master/src/pages/template-parts/sidebar/sidebar.html
```
...
    <ion-item-divider>カテゴリ</ion-item-divider>
    <button menuClose ion-item *ngFor="let p of categories;trackBy:p?.ID" (click)="openPage(p)"  [ngClass]="{'active': p.active}">
      {{p.title}}
    </button>
+    <ion-item-divider>Custom Menu Group</ion-item-divider>
+    <a href='#' target='_blank' menuClose ion-item>Custom Menu</a>
  </ion-list>
</ion-content>
```

**Comment by HsounaZinoubi** [comment]
thank you for your quick reply but what i mean is internal link in-app link
post or page will be rendered in app not opened externally

thanks again

**Comment by rdlabo** [comment]
This is example. 【PageID】is your WordPress Page ID.
```
...
+    <ion-item-divider>Custom Menu Group</ion-item-divider>
+    <button menuClose ion-item (click)="openPage('【pageID】')" [ngClass]="{'active': p.active}">Custom Page</a>
```
This starter package is use default function Ionc and WordPress.com. 
If you want to increase the function, you should look at the document.

https://ionicframework.com/docs/

regards.
